### PR TITLE
Add --rankdir to graph_models

### LINKED ISSUE #1567: rankdir support for graph_models
For some people the way graph_models orders the nodes in `.dot` mode is not very intuitive - the most important 
entity (hospital, country, site) is placed at the bottom of the picture while I would expect it to be placed on the top.

Would it be ok to add a `--rankdir` switch for it? I would contribute the necessary patch.

### PR DESCRIPTION
**Pull request by ppolewicz**
Closes #1567

### CODE REVIEW

**Comment by trbs** [comment]
Thanks ! Could you please update the PR to fix the conflict ?

Also could you please add a test in the test suite and documentation in docs/ for the new feature ?

**Comment by ppolewicz** [comment]
Sorry for the delay - it was a conference season. Conflict is now fixed.

I thought about adding a test but noticed that this is a really, really simple parameter passing and there are two or three parameters like that already, which are not tested, so I'd have to add some machinery for this kind of stuff and tbh I don't think it's really worth it. Do you think it is?

I missed the docs, thanks for pointing it out, will update.

**Comment by OmenApps** [comment]
Looks like there are still several test fails in CI. Maybe needs some additional rework before it can be merged.

**Comment by agoncharov-reef** [comment]
Docs updated, branch rebased on latest `main` branch.
I think previous CI failure was unrelated to changes in this PR. I reran some of the failing tests locally and they passed.
Could anyone please trigger testing workflows?

**Comment by ppolewicz** [comment]
@OmenApps can you please approve the CI?

**Comment by OmenApps** [comment]
@ppolewicz While I have contributed to the package in the past and have a great deal of interest in django-extensions, I have no official authority. I believe @trbs is the only one authorized to complete approvals.

**Pull request merged**
