### PR TITLE
Flag for graph_models to color code relations based on on_delete. (#1604)

### LINKED ISSUE #1604: [feature request] Optional colorization for graph edges based on on_delete criteria
(Admin: Feel free to remove this line, the brackets in the title, and add the actual "feature request" tag)

I've using the visualization command to study the effects of `on_delete` in one of our projects. I generate a simple graph filtering using my apps and then I color the edges in the graph using Gimp. Red is for `CASCADE` and yellow for `PROTECTED`. This allow to study deletion criteria for relations with just a quick look.

I tought that patching the mainstream project was worth it, and here I am.

Do you think it will be a good addition to the model graph command? I don't have time right now for preparing the PR but if someone think this will be useful I will try to find time in the future.

Ofc, is someone wants to do it it will be nice. A quick inspections shown that the model graph class is a good place to start. There is already a simple method a that class that prepares de json for the edges. I think extending the signature of that definition and adding the 'fillcolor' param there will be enough.

### PR DESCRIPTION
**Pull request by PauloRSF**
I implemented a new flag (`--color-code-deletions`) for the graph_models command. It adds custom colors for 'ForeignKey's and 'OneToOneField's edges, based on their on_delete setting. That allows a quick visual understanding of the effects of a model's deletion, as proposed on issue #1604.

This is my first contribution on this project, so, if _anything_ can/should be improved, let me know!

Closes #1604.

### CODE REVIEW

**Comment by OmenApps** [comment]
Looks like a good addition. And you provided tests, so I suspect this will be an easy commit once the maintainers get a chance to take a look!

**Comment by mscheper** [comment]
Thanks! I think it's pretty easy to work out, but are the meanings of the colours documented anywhere?

**Comment by PauloRSF** [comment]
@mscheper It's not explicitly documented anywhere 🧐 It would be good to have it in the rst doc, though

**Comment by mscheper** [comment]
> @mscheper It's not explicitly documented anywhere 🧐 It would be good to have it in the rst doc, though

Yeah, I ended up working it out and putting it in my project's docs. Thanks.

**Pull request merged**
