### PR TITLE
adding default output to graph_models

### PR DESCRIPTION
**Pull request by rjauquet**
Hello. Gave a go at addressing #1204 -- if I'm understanding correctly we just want to output the dotdata directly when neither `pygraphviz` or `pydot` are present.

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !

In the documentation we state that the same functionality is also available without using `-o` at all. https://github.com/django-extensions/django-extensions/blob/master/docs/graph_models.rst

What I would suggest is to add a `--dot` option (or similar) to explicitly write out dotfile data, much like the `--pydot` and `--pygraphviz` options. 

Then we should decide if we only want to write out dot data when `--dot` is specificed with `-o` or automatically such as per the PR although that does break backwards compatibility somewhat if your expecting `graph_models` to fail right now if you do not have the right dependencies installed. We could document an backwards compatiblity break for later releases.

Lastly please update the documentation accordingly and lets add some tests to cover these cases.

Thanks !

**Comment by jonemo** [comment]
I was fishing around the issues list for another reason but noticed #1204 which I ran into just yesterday. Feel free to ignore my drive-by PR comment, but since it's fresh on my mind I'm going to add my 2 cent here:

Based on the output of `manage.py graph_models --help` I would have expected yet another behavior than the ones described in the discussion above:

```
$ python manage.py graph_models --help
usage: manage.py graph_models [-h] [--version] [-v {0,1,2,3}]
                              [--settings SETTINGS] [--pythonpath PYTHONPATH]
                              [--traceback] [--no-color] [--pygraphviz]
                              [--pydot] [--disable-fields] [--group-models]
                              [--all-applications] [--output OUTPUTFILE]
                              [--layout LAYOUT] [--verbose-names]
                              [--language LANGUAGE]
                              [--exclude-columns EXCLUDE_COLUMNS]
                              [--exclude-models EXCLUDE_MODELS]
                              [--include-models INCLUDE_MODELS]
                              [--inheritance] [--no-inheritance]
                              [--hide-relations-from-fields]
                              [--disable-sort-fields] [--json]
                              [app_label [app_label ...]]

Creates a GraphViz dot file for the specified app names. You can pass multiple
app names and they will all be combined into a single model. Output is usually
directed to a dot file.

positional arguments:
  app_label

optional arguments:
[...]
  --pygraphviz          Use PyGraphViz to generate the image.
  --pydot               Use PyDot(Plus) to generate the image.
[...]
  --output OUTPUTFILE, -o OUTPUTFILE
                        Render output file. Type of output dependend on file
                        extensions. Use png or jpg to render graph to image.
[...]
  --json                Output graph data as JSON
```

> Render output file. Type of output dependend on file extensions. Use png or jpg to render graph to image.

This suggests that the output format is chosen based on file extension. I would have expected that `-o myfile.dot` works without pygraphviz or pydot and writes a .dot file (same as #1204). 

Similarly, I would expect that `-o myfile.json` works without pygraphiviz or pydot. It does not, but `--json -o myfile.json` does.

Two possible conclusions:
* Introduce `--dot` flag as suggested by @trbs. Clarify help output for `-o` option to no longer state "Type of output dependend on file extensions"
* Keep "Type of output dependend on file extensions" help text and handle `.json` and `.dot` file extensions separately, dropping need for `--json` (but keeping it for backward compatibility).

**Comment by trbs** [comment]
Thanks @jonemo 

I really like automatically choosing the format based on the extension if no other cli option is given.

And why not do both :-) if no other option is given base the format on the extension of the file. I can imaging certain workflows where people do `./manage.py graph_models -a --json --output /some/temp.file` which might not necessarily then end with `temp_file.json`.

@rjauquet or @jonemo are you able to update the PR ?

**Comment by jonemo** [comment]
> are you able to update the PR ?

@trbs: I'll open a PR within the next days. I have something working but need to familiarize myself with how testing works in this project :)

**Pull request closed without merging**
