### PR TITLE
Fix SubfieldBase deprecation warning

### PR DESCRIPTION
**Pull request by jpadilla**
Attempt at fixing: `RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.`

### CODE REVIEW

**Comment by jpadilla** [comment]
Hopefully I'll get to fixing whatever is wrong here by next week.

**Comment by trbs** [comment]
This might relate to https://github.com/django-extensions/django-extensions/issues/781 as well since JSONField is still broken for Django 1.9.

**Comment by danpalmer** [comment]
@jpadilla hey, just wondering if you were still working on this? @trbs would be good to get this fixed up and merged.

**Comment by trbs** [comment]
@danpalmer can you confirm that this PR is the correct fix ?
@jpadilla can you update the PR and fix the build failure ?

**Comment by danpalmer** [comment]
@trbs it looks right, according to the Django docs. The test failure is legit though and needs addressing, but apart from that this looks good.

**Comment by jpadilla** [comment]
If anyone has the time to pick this up that'd be great. Won't be able to get much work put into this at the moment. :(

**Comment by timgraham** [comment]
Updated in https://github.com/django-extensions/django-extensions/pull/914.

**Comment by trbs** [comment]
Should be fixed now. Sorry that this took some time.
Thanks for everybody's help on this ! :)

**Pull request closed without merging**
