### PR TITLE
Use TOXENV variables in `travis.yml`

### PR DESCRIPTION
**Pull request by benjaminabel**

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !

**Comment by benjaminabel** [comment]
@trbs Would you like to use django py.test in your test suite?

**Comment by trbs** [comment]
@benjaminabel maybe we can take this to https://github.com/django-extensions/django-extensions/issues/454 ?

There we have a small discussion on the way we currently do testing. I think moving to py.test and their best practices might be very good move to improve our test(runner).

**Comment by benjaminabel** [comment]
@trbs so you seem ok.  Moving to #454

**Comment by trbs** [comment]
Great thanks

**Pull request merged**
