### PR TITLE
Support ptpython>=v0.27.

### PR DESCRIPTION
**Pull request by ryneeverett**
Ptpython was moved to a separate package in v0.27

### CODE REVIEW

**Comment by ryneeverett** [comment]
Assuming the CI failures aren't my fault.

**Comment by trbs** [comment]
Could you please make this change backwards compatible ?
So that it does not break for existing users with the old prompt-tool package.

Thanks

**Comment by ryneeverett** [comment]
@trbs It is backwards compatible. Just tested with prompt-toolkit v0.26

**Comment by trbs** [comment]
I think I completely read over the second ```try-except ImportError```.

Thanks !

**Pull request merged**
