### PR TITLE
RandomCharField - Prepopulates random character string.

### PR DESCRIPTION
**Pull request by dpetzold**
Hello,

I added support for a random character field. Its purpose is to create an unique id unrelated to the database id to prevent site walking and sequential attacks on something like a unsubscribe link.  A sample use case would be a link shortening service like bit.ly, http://bit.ly/1AbL4UC.

Non-Breaking changes:
- Factored out query logic to ensure uniqueness to BaseUniqueField.
- The field value factories have been moved to generators.
- Added mock as a test requirement.

Possibly breaking change:
- The slug field check will only be tried 100 times. Previously there was no limit. That was done because the field value factories have been moved to a generators.

Please let me know your comments and feedback. I enjoyed working on this code very much!

### CODE REVIEW

**Comment by trbs** [comment]
Could you please take a look at why the tests are failing ?
(Sorry I don't have the time right now to dive into this)

**Comment by dpetzold** [comment]
Its from this

    ValidationError: [u'The verbose_name of random char test model lower alpha digits is longer than 39 characters']

I'll fix and try to increase coverage.

**Comment by trbs** [comment]
Ready to merge ?

**Comment by dpetzold** [comment]
Yeah this is it.

**Comment by dpetzold** [comment]
Sorry I have been changing history to keep the commit clean. That is why its rebuilding.

**Comment by trbs** [comment]
Thanks !! :)

**Pull request merged**
