### PR TITLE
Support Django 2.2 UniqueConstraint.condition 

### PR DESCRIPTION
**Pull request by yeojin-dev**
Issue #1384

### CODE REVIEW

**Comment by yeojin-dev** [comment]
The code I've worked on cannot pass the test in mysql environment only. I don't know why. Do you have any idea why? @trbs

**Comment by trbs** [comment]
> The code I've worked on cannot pass the test in mysql environment only. I don't know why. Do you have any idea why? @trbs

https://docs.djangoproject.com/en/3.0/ref/models/indexes/#django.db.models.Index.condition

Seems MySQL does not support this at all.
Looks like its safe to also skip the tests if MySQL is being used.
(Wondering if we should raise an exception to let the user know it's not going to work as expected, however Django itself also seems to silently ignore the condition.)

**Comment by yeojin-dev** [comment]
Thanks. I fixed it. :) @trbs

**Comment by trbs** [comment]
Thanks !

**Pull request merged**
