### PR TITLE
Added information about the Django Admin Generator

### PR DESCRIPTION
**Pull request by WoLpH**

### CODE REVIEW

**Comment by trbs** [comment]
Could you please fix the flake8 error ?

**Comment by WoLpH** [comment]
Yes, I will :)

That's what I get for creating pull requests using nothing but the github interface ;)

**Comment by WoLpH** [comment]
Ok, fixed now :)

**Comment by trbs** [comment]
Great, thanks !

**Comment by SalahAdDin** [comment]
Interesting.

**Pull request merged**
