### PR TITLE
Use list values for requires_system_checks

### PR DESCRIPTION
**Pull request by danlamanna**
See the changes in Django 4.1 for https://docs.djangoproject.com/en/dev/releases/4.1/#features-removed-in-4-1.

### CODE REVIEW

**Comment by ulgens** [comment]
Can you please add Django 4.1 to the test matrix, so we know it works fine?

**Comment by philippbosch** [comment]
@danlamanna I think what @ulgens means is this:
https://github.com/philippbosch/django-extensions/commit/c7aa2c3460e58a0be4e5ebd6967a28dff3063cc6
Would be great if you could add this to this PR. Thank you!

**Review by ulgens — APPROVED** [review]

**Review by philippbosch — APPROVED** [review]

**Comment by spapas** [comment]
Hello friends, is there a reason this PR isn't merged yet? It's more than two months since @danlamanna opened it and it's a very small change.

Can I do anything to help merge it and release a new  version quicker ? 

Thank you

**Comment by trbs** [comment]
Let's fix the small mypy / linter error :-)

**Comment by danlamanna** [comment]
> Let's fix the small mypy / linter error :-)
> 
> `Need type annotation for "requires_system_checks" (hint: "requires_system_checks: List[<type>] = ...")`

@trbs done.

**Comment by trbs** [comment]
Thanks !

**Pull request merged**
