### PR TITLE
Ticket 1394 -- Used lower case fields for MySQL

### PR DESCRIPTION
**Pull request by nasirhjafri**
connects https://github.com/django-extensions/django-extensions/issues/1394

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !

I would like to ask if you might want to write a test for this ?
If so please put it in another PR and I will add a test target that runs against`mysql` in travis.

**Comment by nasirhjafri** [comment]
Sure, I'll create another PR for test.

**Comment by LanghaniKuldeep** [comment]
@trbs I have added test cases for this in this [PR](https://github.com/django-extensions/django-extensions/pull/1399)

**Comment by trbs** [comment]
Awesome thanks !

**Pull request merged**
