### PR TITLE
Add fix & tests for JSONField

### PR DESCRIPTION
**Pull request by Stranger6667**
I've found some issues with JSONField and want to discuss expected behaviour

### CODE REVIEW

**Comment by Stranger6667** [comment]
Should `None` value be saved as JSON `null` or as SQL `NULL` ?
String `foo` will be encoded like `"foo"` and it will be valid JSON value, and will be decoded correctly as well. Is it expected behavior on such input values?

**Comment by Stranger6667** [comment]
If #818 will be merged, then all tests will pass. I've changed some behavior of JSONField.
Also I want to add more tests (e.g. on `update()`)

**Comment by trbs** [comment]
I committed a few of your changes to fix the JSONField tests.
Would like to get other people testing this so we can be sure it does not break anything.

After that lets merge the other changes and discuss fixes/improvement that changes the behavior of JSONField.

**Comment by Stranger6667** [comment]
Sounds cool! I'll do rebase and adapt these changes

**Comment by trbs** [comment]
Sorry for having to rebase.

**Comment by Stranger6667** [comment]
Hello! Any news? :)

**Comment by Stranger6667** [comment]
As friendly reminder :) any feedback? Are these changes OK?

**Comment by trbs** [comment]
Sorry for the (far too) late reply.
It's been busy, don't we all wish that we could make this our day job ? :-)

Does this PR still changes the behavior of the JSONField (in a backwards incompatible way) ?
And does fix things that are still broken ?

**Comment by wsantos** [comment]
@Stranger6667 @trbs any update on this ?

**Comment by wsantos** [comment]
I've tested and django 1.9.X with django-extensions 1.5.x is also broken.

```python
Python 2.7.10 (default, Sep 23 2015, 04:34:21)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> xa = TestJson.objects.create(json={'a': 1})
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/query.py", line 401, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/base.py", line 708, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/base.py", line 736, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/base.py", line 820, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/base.py", line 859, in _do_insert
    using=using, raw=raw)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/backends/utils.py", line 83, in execute
    sql = self.db.ops.last_executed_query(self.cursor, sql, params)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/backends/sqlite3/operations.py", line 140, in last_executed_query
    params = self._quote_params_for_last_executed_query(params)
  File "/Users/wsantos/.virtualenvs/dpool/lib/python2.7/site-packages/django/db/backends/sqlite3/operations.py", line 129, in _quote_params_for_last_executed_query
    return cursor.execute(sql, params).fetchone()
InterfaceError: Error binding parameter 0 - probably unsupported type.
>>> import django
>>> import django_extensions
>>> django.VERSION
(1, 9, 7, 'final', 0)
>>> django_extensions.VERSION
(1, 5, 9)
>>>
```

**Comment by trbs** [comment]
Is this still a problem ?

**Pull request closed without merging**
