### PR TITLE
Make it possible to parse https github urls in pipchecker

### PR DESCRIPTION
**Pull request by vstoykov**
Make it possible to parse URLs In pipchecker command of the following format:
```
https://github.com/django/django/archive/393c268e725f5b229ecb554f3fac02cfc250d2df.tar.gz#egg=Django
https://github.com/django/django/archive/393c268e725f5b229ecb554f3fac02cfc250d2df.zip#egg=Django
https://github.com/django/django/archive/master.tar.gz#egg=Django
https://github.com/django/django/archive/master.zip#egg=Django
https://github.com/django/django/archive/1.5b2.tar.gz#egg=Django
https://github.com/django/django/archive/1.5b2.zip#egg=Django
```

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !

**Comment by trbs** [comment]
(p.s. if you want / have some time it would be awesome to have some unittests for the code in pipchecker :) )

**Comment by vstoykov** [comment]
@trbs I also thought that will be good to have some tests for pipchecker because currently there are none and overral coverage of the project is very low.

I can try to refactor the code in order to be more easy to test (at least requirements.txt parsing part), and include some tests.

**Comment by trbs** [comment]
That will be very much appreciated !

**Pull request merged**
