### PR TITLE
Migrate to pytest

### LINKED ISSUE #454: Test Runner Issue
Somehow django 1.6 does not run all the tests:

https://travis-ci.org/django-extensions/django-extensions/jobs/16780166#L132

It was running only 6, meanwhile other django versions where running 35 tests:

https://travis-ci.org/django-extensions/django-extensions/jobs/16780167#L173

So I have made this change https://github.com/django-extensions/django-extensions/commit/5285fd664c7ff4c0fee98aef03de8d1d91b22c1d

It works for django 1.6 but somehow does not work for django 1.5 and 1.4:

https://travis-ci.org/django-extensions/django-extensions/builds/16789212

Maybe the best solution would be to change the way we use the test runner, but since I don't know much about it I'll leave it here.

### PR DESCRIPTION
**Pull request by benjaminabel**
This PR fixes #454, #570 using `pytest django` to run the tests, py.tests finds 54 tests in all tox environments.

- test directory has been moved to root directory.
- runtest.py script has been removed in favor of a configuration test via a `conftest.py` file
- tests files has been renamed to `test_...`
- Use django.test.TestCase when database access is necessary
- uses pytests fixtures and decorators.
- remove old uuid utils tests used for python<2.5
- import keyczar in tox for python 2.7 and pass tests for django>=1.7.
- cleaned imports in tests
- renamed test functions to underscore

@camilonova  @trbs Everything's ok, I can rebase in one commit if you prefer.

### CODE REVIEW

**Comment by camilonova** [comment]
@benjaminabel You are awesome!

**Comment by trbs** [comment]
Nice ! Thanks @benjaminabel  !

**Comment by ticosax** [comment]
:+1:

**Comment by benjaminabel** [comment]
@camilonova @trbs You're welcome. Thanks for this useful package.

**Pull request merged**
