### PR TITLE
added ipdb, pdb and wdb filters

### PR DESCRIPTION
**Pull request by kuter**
Hello, I'd like to add templatetags for debugging Django templates. If you like that idea I will add some docs and unittest.

### CODE REVIEW

**Comment by trbs** [comment]
Could you please add a few lines of documentation for how to use those template tags ?

**Comment by trbs** [comment]
Happy to merge this PR.

Just not entirely sure how one would use them :-)

**Comment by kuter** [comment]
I've added documentation and unit test.

**Comment by trbs** [comment]
awesome thanks !

**Pull request merged**
