### PR TITLE
Reduce reraise pollution in runserver_plus traceback page

### PR DESCRIPTION
**Pull request by jhselvik**
For issue #1201. 

It felt a little hacky but I couldn't figure out a better way to do it, I'm open to suggestions. I tested on 2.7 and 3.7. The output looks much better now.

image

### CODE REVIEW

**Comment by trbs** [comment]
Should we also clear the global `wsgi_tb` at the end ?

I agree with your comments... feels a bit hacky.. but also I don't have a better answer (or time to see if there is any) at the moment :-)

**Comment by jhselvik** [comment]
That's a good idea, but I'm not sure sure where the end would be. After `null_technical_500_response` re-raises it goes back to the Django code outside of this repo.
 
Each time `null_technical_500_response` is called on Middleware objects it checks to see if it is for a WSGIHandler object. If so it saves the traceback to display. Because of this I believe it should have the correct traceback for each new WSGI request. I tested with consecutive WSGI calls and it work without clearing.

**Comment by trbs** [comment]
Yeah your probably right but still feels kinda "wrong" :-)

Thinking this is very likely also not thread safe. Sure `runserver_plus` should not be used in such a way that this is a real issue (aka in production) but still...

Using thread.local should solve that... (but kinda also feels like a kludge)

As for clearing the global var this would work:
```
    if isinstance(tb.tb_next.tb_frame.f_locals['self'], WSGIHandler):
        wsgi_tb = tb
    elif wsgi_tb:
        tb = wsgi_tb
        wsgi_tb = None
    six.reraise(exc_type, exc_value, tb)
```

Makes it a bit cleaner, clears up the wsgi_tb after using it and removed the duplicate `six.reraise`

**Comment by jhselvik** [comment]
Alright, thanks for taking a look. You're right, I did not consider thread safety.

I am traveling today, but will try and wrap this up with another commit by the end of the weekend. Will clean up the code as mentioned above and look into using thread.local.

**Comment by jhselvik** [comment]
Clearing the global var as mentioned above did not suppress the repeated re-raises in the traceback. `null_technical_500_response` is called on every Middleware object in a stack and after it is called on the WSGI Middleware object the global var was cleared. The WSGI object is called first in the stack, so for the following seven or so `null_technical_500_response` calls the re-raise problem remained because of the global var getting cleared.

However, I removed the global var in favor of threading.local. This is a bit cleaner, but technically still doesn't clear the now thread's wsgi_tb variable. If the threading option is configured each request should have its own thread and is probably not an issue.

**Comment by trbs** [comment]
@jhselvik thanks a lot for all your help on this issue !

**Pull request merged**
