### PR TITLE
1.) Fixed issue with exclusion of directories - directories beneath r…

### PR DESCRIPTION
**Pull request by khirstinova**
Fixed issue with sync_s3 and --filter-list exclusions.  Did not exclude sub-directories of excluded directories.

### CODE REVIEW

**Comment by trbs** [comment]
You think it's possible to add some tests for this ?

**Comment by khirstinova** [comment]
I added a good test that took me four hours to make - that's all my employer will let me do for this.  Let me know, but if possible can we close so I don't have to pull from a forked repo too much longer?

**Comment by trbs** [comment]
Looks like there are issues with Travis.

There seems to be some style errors but Travis won't show the logs for me.

Please fix the style errors if they are real.

**Comment by khirstinova** [comment]
This looks like Travis is having an error setting up a virtual environment for some reason.  This seems to be why it's failing.  Don't know how to fix that.

New pypy executable in /home/travis/build/django-extensions/django-extensions/.tox/pypy3-djmaster/bin/pypy3
Also creating executable in /home/travis/build/django-extensions/django-extensions/.tox/pypy3-djmaster/bin/pypy
Installing setuptools, pip, wheel...
  Complete output from command /home/travis/build/d...3-djmaster/bin/pypy3 - setuptools pip wheel:
  Collecting setuptools
  Downloading setuptools-30.1.0-py2.py3-none-any.whl (472kB)
Collecting pip
/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.5
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/travis/build/d...3-djmaster/bin/pypy3 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /opt/python/pypy3-2.4.0/bin/pypy3
ERROR: InvocationError: /home/travis/virtualenv/python3.5.2/bin/python -m virtualenv --python /opt/python/pypy3-2.4.0/bin/pypy3 pypy3-djmaster (see /home/travis/build/django-extensions/django-extensions/.tox/pypy3-djmaster/log/pypy3-djmaster-0.log)
___________________________________ summary ____________________________________
ERROR:   pypy3-djmaster: InvocationError: /home/travis/virtualenv/python3.5.2/bin/python -m virtualenv --python /opt/python/pypy3-2.4.0/bin/pypy3 pypy3-djmaster (see /home/travis/build/django-extensions/django-extensions/.tox/pypy3-djmaster/log/pypy3-djmaster-0.log)
The command "tox -e $TOX_ENV" exited with 1.

**Comment by khirstinova** [comment]
Travis CI is crazy slow.  I can't really figure out why it's not passing on a second build.  Is Travis dependent on S3?

**Comment by khirstinova** [comment]
Travis CI finally started responding and I think the style issues are fixed.

**Comment by trbs** [comment]
Thanks !

**Pull request merged**
