### PR TITLE
Added an option to disable the pin in werkzeug.

### PR DESCRIPTION
**Pull request by deese**
Disable the pin with the following parameter:

./manage.py runserver_plus --nopin

I know that can be insecure, but for local developing it helps a lot.

### CODE REVIEW

**Comment by trbs** [comment]
Could you make the PR such that it will work with both 0.10.x and 0.11.x ?
Also if you could add just a couple of lines in the documentation, about what this is ?
(Like a small paragraph explaining what this is and a link to the werkzeug docs about the pin security feature)

Thanks !

**Comment by deese** [comment]
After reviewing the documentation, the pin can be disabled with an environment variable (http://werkzeug.pocoo.org/docs/0.11/debug/#debugger-pin) 

Do you think that this patch is needed? Maybe not.

I have an update of the patch, so if you think is something useful I can make the PR.

Thanks!

**Comment by trbs** [comment]
I have no problem with the option in the command as long as it's backwards compatible with people running 0.10.x versions.

**Comment by trbs** [comment]
bump, happy to merge that updated patch (assuming that it will be backwards compatible) if you want.

**Comment by FeroxTL** [comment]
+1 for this option

**Comment by deese** [comment]
I just changed the patch. As it's using the environment variable, it will work with any version.  Sorry for the delay, I just lost track of this :)

**Comment by trbs** [comment]
Think the PR needs to be rebased to current master version...

**Comment by deese** [comment]
I did it, but the PR is showing both commits. I will close this PR and create a new one.

**Pull request closed without merging**
