### PR TITLE
Display correct error message for missing imports

### PR DESCRIPTION
**Pull request by kevgathuku**
When a missing import is found in a script, this changes the error
message displayed to indicate that there's a missing import, rather than
giving a generic error message similar to the one raised when the script
does not exist

For a case such as this:
`test_script.py`

``` python
import nonexistrentpackage

def run():
    print("Test")
```

The error message raised previously was:

```
No (valid) module for script 'test_script' found
Try running with a higher verbosity level like: -v2 or -v3
```

This changes the error to be more descriptive, without requiring the user to change the default verbosity mode, i.e.

```
Cannot import module 'scripts.test_script': No module named nonexistent.
No (valid) module for script 'test_script' found
Try running with a higher verbosity level like: -v2 or -v3
```

### CODE REVIEW

**Comment by kevgathuku** [comment]
Hey @trbs don't mean to be a bother, but have you had a chance to look at this patch? It fixes issue #955
Is there anything else I could do to make it better?

**Comment by trbs** [comment]
@kevgathuku no problem. I was traveling over the last few days so I did not get the time to look at PR's.

Not really sure why AttributeError and ImportError where caught here originally. I think we can split it up in two ```except``` sections. As I think now an AttributeError in the script will show the message as if it where an ImportError.

Also thinking; why not just let the import script throw it's original errors ? and get rid of the try-except altogether ?

The purpose of the try-except statement here only seems to be to catch if the script exists or not.. 
For that we could also use something like ```importlib.util.find_spec(mod)```, ```pkgutil.find_loader(mod)``` or ```imp.find_module(mod)```.

Wouldn't that be even better ?

**Comment by kevgathuku** [comment]
Hi @trbs,
Thanks for the reply. I would need to look into those options first, in order to understand the options we could use.

**Comment by kevgathuku** [comment]
Hey @trbs seems I'm working on this now again. Apologies for the extremely long wait.
It seems the `AttributeError` was introduced in this commit: https://github.com/django-extensions/django-extensions/commit/fc6722dac01119d5c26125330a5a741c9f644869

I think the key thing now is differentiating when a script raises an import error vs when a script is not found. 
Right now, a valid script will not be added to [`modules`](https://github.com/django-extensions/django-extensions/blob/master/django_extensions/management/commands/runscript.py#L156) if it raises an `ImportError`. 
Making that distinction is what I'm working on right now. Expect an update on that soon.

**Comment by kevgathuku** [comment]
I've opted to raise the error if an invalid import is found in one of the scripts. Let me know what you think of this approach.

**Comment by kevgathuku** [comment]
On the other hand, I am having some trouble testing the invalid imports. I keep getting this error, even in the collect tests phase. Any idea on how to prevent the script from being run before the tests run?
image

**Comment by trbs** [comment]
Very late reply 🥇 :-)

I think this is because `py.test` is searching for docstrings, it scans through all the files to do that. You can exclude specific files in `setup.cfg` so that it will not error out on  `invalid_import_script.py`.

**Comment by trbs** [comment]
Thanks !

**Comment by kevgathuku** [comment]
Hey @trbs thanks for merging, but there's still some pending issues that I noticed I didn't fix 😅 
This is mostly caused by `importlib.import_module` behaving differently after Python 3.3.
I'll fix that and open another PR with some more tests 😄

**Comment by trbs** [comment]
Thanks a lot !

**Pull request merged**
