### PR TITLE
Add syntax highlighting when printing SQL

### PR DESCRIPTION
**Pull request by maxnordlund**
This uses the excellent pygments library to to the heavy lifting. In the process of adding this to both the runserver and shell command, the few differences between them are unified.

skarmavbild 2017-05-03 kl 15 40 44

### CODE REVIEW

**Comment by trbs** [comment]
Very cool !

For the commit I'm wondering are we missing the print / logger lines for `raw_sql` ?

**Comment by maxnordlund** [comment]
Whops, you're completely right, I must've deleted them by accident. I'll fix that right away.

**Comment by trbs** [comment]
Thanks !

**Comment by maxnordlund** [comment]
No problem 😸

**Pull request merged**
