### PR TITLE
proposal for issue #1577

### PR DESCRIPTION
**Pull request by sdementen**
To allow to have default app_labels in the GRAPH_MODELS:
- added option --app-labels accepting one or more arguments
- get default for app-labels from GRAPH_MODELS["app-labels"]
- support both --app-labels and positional arguments for app_label

### CODE REVIEW

**Comment by trbs** [comment]
Could you make this simpler ?
Thinking that some thing like this would be enough:
```diff
diff --git a/django_extensions/management/commands/graph_models.py b/django_extensions/management/commands/graph_models.py
index 8cb4a57..6da4a08 100644
--- a/django_extensions/management/commands/graph_models.py
+++ b/django_extensions/management/commands/graph_models.py
@@ -195,7 +195,11 @@ class Command(BaseCommand):
     def handle(self, *args, **options):
         args = options['app_label']
         if not args and not options['all_applications']:
-            raise CommandError("need one or more arguments for appname")
+            default_app_labels = getattr(settings, 'GRAPH_MODELS', {}).get("APP_LABELS")
+            if default_app_labels:
+                args = default_app_labels
+            else:
+                raise CommandError("need one or more arguments for appname")

         # Determine output format based on options, file extension, and library
         # availability.
```

Also we need to update the docs as well..

**Comment by sdementen** [comment]
you're right, much simpler!
what do you want me to do? another PR ? or you convert your patch in a PR ?

**Comment by sdementen** [comment]
is this better ? I used app_labels instead of APP_LABELS to be consistent with the casing of the other options

**Comment by trbs** [comment]
Thanks !

**Pull request merged**
