### PR TITLE
removed passwd management command

### PR DESCRIPTION
**Pull request by kuter**

### CODE REVIEW

**Comment by trbs** [comment]
Could you explain the reason for this PR please ?

**Comment by kuter** [comment]
@trbs I believe that this command was useful few years ago .. nowadays we've got build-in changepassword command.

**Comment by trbs** [comment]
I understand... I would like to deprecate the command first for couple of releases instead of outright removing it. (Steps should probably be... print warning for couple of releases with functioning command, then only print warning and exit, then remove completely)

**Comment by kuter** [comment]
I've created new PR #1331 which add deprecation warning and print that warning for passwd command.

**Comment by trbs** [comment]
Awesome ! I merged that and build failures should stop soon as well :-)

**Pull request closed without merging**
