### PR TITLE
Fix call grind format to enable source code navigation in qcachegrind.

### PR DESCRIPTION
**Pull request by shuoli84**
ref: https://kcachegrind.github.io/html/CallgrindFormat.html

The filename should be in a separated line e.g "fl", "cfl".

### CODE REVIEW

**Comment by shuoli84** [comment]
Here is the screenshot after the fix.
screen shot 2016-02-28 at 10 20 07 pm

**Comment by shuoli84** [comment]
Open an issue related with this pull request. issue #847

**Comment by trbs** [comment]
Is this a change in the format or a straight out bug ?

Aka could this break people (now) working setups ?

**Comment by shuoli84** [comment]
@trbs I treat it as a bug, since for current version, I can't make qcachegrind work properly. But not sure whether some other people already rely on current format. Anyway, this only affect the callgrind profile, so should be ok.

**Comment by trbs** [comment]
Thanks for the patch.

**Pull request merged**
