### PR TITLE
Allow Jupyter Kernel to installed under venv

### LINKED ISSUE #1378: Jupyter Kernel installed under Library/Jupyter  rather than virtual environment
I have a Django project that uses pipenv to manage its virtual environment, in which I have installed Jupyter and "django-extensions" and run `/manage.py shell_plus --notebook`.

It seems the "django_extensions" jupyter kernel gets installed in `Library/Jupyter/kernerls`, making is accessible to other jupyter projects. By contrast, it seems like the python3 kernel is installed within the virtual environment.

Here is what I see when running `jupyter kernelspec list`, inside my project `cc-dashboard` with its respective pipenv activated.

```bash
jupyter kernelspec list

Available kernels:
  django_extensions    /Users/dustinmichels/Library/Jupyter/kernels/django_extensions
  python3              /Users/dustinmichels/.local/share/virtualenvs/cc-dashboard-15QDmC0q/bin/../share/jupyter/kernels/python3
```

Is there a way to get the kernel to install itself under the virtual environment's `share/jupyter` folder instead? Thanks.

## Specs

- **django** -- version: 2.2.1
- **django-extensions** -- version: 2.1.7
- **jupyter** -- version: 4.4.0
- **python** -- version: 3.7.3
- **pipenv** -- version 2018.11.26
- **OS** -- MacOS Mojave (10.14.5)

### PR DESCRIPTION
**Pull request by trbs**
Add command line option `--use-venv-kernel-spec-dir` and settings file option `SHELL_PLUS_USE_VENV_KERNEL_SPEC_DIR` to control if the kernel spec file is created under `ksm.user_kernel_dir` or the jupyter kernel location under the virtual env (if available).

Fixes  #1378

### CODE REVIEW

**Comment by trbs** [comment]
@dustinmichels could you test this for me please ?

**Comment by terencehonles** [comment]
@trbs while this looks good to me, I just created #1509 (which is touching the same area of code) and I had a thought to contribute.

The request in #1500 is to make sure the spec is created in the same place the base spec is taken from (if possible), and I looked at the kernel spec object (`ks`) and there is a `ks.resource_dir` which would point to where the original kernel spec was loaded from. I could edit #1509 to first try writing to a sibling `resource_dir` and if it can't write there fall back to the user dir (with a logged warning).

Thoughts?

**Comment by terencehonles** [comment]
I went ahead and incorporated my changes, and am testing my PR with the updates.

**Comment by trbs** [comment]
Sorry could you update the PR please ?

**Comment by terencehonles** [comment]
> Sorry could you update the PR please ?

Yeah I can to that but this PR is superceded by #1509 which is already merged

**Comment by trbs** [comment]
Check 👍 

Thanks for all your help !

**Pull request closed without merging**
