### PR TITLE
Added "managestate" command

### PR DESCRIPTION
**Pull request by KazakovDenis**
Hi!

I use this command in my projects and have decided it may make use to others. I saw that a quite similar [pull request](https://github.com/django-extensions/django-extensions/pull/1362) is still not accepted, rethought the idea a little, and described the profit of this feature in the [documentation](https://github.com/django-extensions/django-extensions/commit/696f6fb553e41b4fd9bc834bfddfafea11467043). 

I also took into account comments under that pull request and added the necessary tests.

Hope this may be useful!

### CODE REVIEW

**Review by camilonova — APPROVED** [review]

**Comment by ulgens** [comment]
@camilonova @KazakovDenis Don't we need this new command mentioned under https://github.com/django-extensions/django-extensions/blob/main/docs/command_extensions.rst ?

**Comment by trbs** [comment]
https://github.com/django-extensions/django-extensions/commit/ff8a9a73e6eb6f700cfb4e1db42771cbf2d525ad
and
https://django-extensions.readthedocs.io/en/latest/command_extensions.html
:-)

**Comment by ulgens** [comment]
@trbs Thank you 🌷

**Comment by blueyed** [comment]
Just for reference: https://pypi.org/project/stellar/ can be used to manage/create snapshots of PostgreSQL also.

**Pull request merged**
