### PR TITLE
removed truncate_letters templatetag

### PR DESCRIPTION
**Pull request by kuter**

### CODE REVIEW

**Comment by trbs** [comment]
Would like to deprecate the filter first then remove it later.

Could you create a seperate pull request for the change in `tests/test_management_command.py` ?

**Comment by kuter** [comment]
@trbs I've separate change in test/test_management_command.py and created new PR #1304 .
I've added deprecation warning and used truncatechars from django.

**Comment by trbs** [comment]
Could you please rebase so we can merge this ? :-)

**Comment by kuter** [comment]
> Could you please rebase so we can merge this ? :-)

**Comment by kuter** [comment]
> Could you please rebase so we can merge this ? :-)

I've tried but probably something went wrong .. feel free to rebase that branch by you own. Thanks ;)

**Comment by trbs** [comment]
Committed the changes in 79b31a648cacc7ab833d4f1636eaa9594a210f07

**Pull request closed without merging**
