### PR TITLE
Fixed 'Error binding parameter 2' in Django 1.9

### PR DESCRIPTION
**Pull request by szok**

### CODE REVIEW

**Comment by trbs** [comment]
The last patch for this caused side effects... can people test this (and/or create more tests) so we are sure this works correctly for everybody ?

**Comment by szok** [comment]
I tested only for Django 1.9.
According to unit testing should work other version

**Comment by trbs** [comment]
The unit tests are not covering all cases. There is a PR for some additional tests here: https://github.com/django-extensions/django-extensions/pull/793

**Comment by trbs** [comment]
I do not want to merge anything that is not thoroughly tested....

**Comment by szok** [comment]
Ok, tests added.

**Comment by brianmay** [comment]
What is the status of this pull request? The tests appear to pass after installing making this change.

**Comment by trbs** [comment]
Think the status is still the same... Either somebody needs to be able to explain why this change is correct and why it won't break anything and/or it needs to be thoroughly tested.

**Comment by brianmay** [comment]
I assume you mean the test cases already added by @szok on 5th Jan are insufficient?

**Comment by camilonova** [comment]
@szok Can you please check the conflicts?

**Comment by szok** [comment]
@camilonova Yes, it will be on Monday

**Comment by szok** [comment]
@camilonova Done :)

**Comment by camilonova** [comment]
@szok Thanks man

**Pull request merged**
