### PR TITLE
fix: Handle warnings for default_app_config

### LINKED ISSUE #1649: RemovedInDjango41Warning: 'django_extensions' defines default_app_config
The following warning is emitted when using django-extenstions along with django 3.2
```
django.utils.deprecation.RemovedInDjango41Warning: 'django_extensions' defines default_app_config = 'django_extensions.apps.DjangoExtensionsConfig'. Django now detects this configuration automatically. You can remove default_app_config.
```

I suppose it is related to the change introduced by django 3.2: https://docs.djangoproject.com/en/3.2/releases/3.2/#what-s-new-in-django-3-2

Environment:
* python 3.8
* django 3.2

### PR DESCRIPTION
**Pull request by abhiabhi94**
- they are only defined for django versions < 3.2

closes #1649

### CODE REVIEW

**Comment by abhiabhi94** [comment]
I think a couple of other warnings for django41 and django40 can be fixed. would it be wise to do it in a separate commit?

**Comment by trbs** [comment]
Yeah lets open a new one for 4.0 and 4.1 related warnings.
Then I'll merge this one :-)

**Comment by trbs** [comment]
Thanks !

**Comment by abhiabhi94** [comment]
i have opened another one for 4.0 and 4.1 warnings at #1656.

**Pull request merged**
