### PR TITLE
Added support for Django 4.1.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by philippbosch** [comment]
Duplicate of #1736, but this one here looks more comprehensive …

**Comment by felixxm** [comment]
I missed #1736, sorry.

**Comment by trbs** [comment]
Sorry https://github.com/django-extensions/django-extensions/pull/1736 was merged before this one.

If there is any part of this that we are now missing could you please create a new PR or re-open and rebase this one ?

**Comment by felixxm** [comment]
I opened rebased PR, see #1763.

**Pull request closed without merging**
