### PR TITLE
Transition command files to argparse compatibility.

### PR DESCRIPTION
**Pull request by thecardcheat**
Issue #788.

I wanted feedback on this patch regarding a few things before putting more time in:

1) Are you cool with this method? This seems a lot more sensible to me than maintaining two argument lists in every management command file. It seems that BaseCommand simply uses the presence of an option_list to determine what course to take.

2) In my _extremely_ brief testing, everything seemed kosher in 1.9.1 and 1.7.11 using actual types for the type kwarg in optparse (e.g. the indent arg in print_settings; this is what argparse wants), despite the optparse doc only mentioning strings. Anyone know the deal here? Please point out any major pitfalls you see that I might have missed.

### CODE REVIEW

**Comment by thecardcheat** [comment]
Also for clarity because I allowed the pull request title to be misleading, my intent was to do this project-wide - I just wanted initial feedback.

**Comment by trbs** [comment]
Yes, I think this is a clean way of doing it. It's very nice that we can use the ```def add_arguments``` everywhere and still be backwards compatible. Also removing this code in the future will be straight forward.

I think we can deal with any pitfall that might arise. Also Django 1.7 is now officially unsupported since 1 December 2015. So we don't have to be super strict about supporting it, although I always like it when we can be friendly to previous versions :)

Please update the patch and I will merge it in.
Thanks for your work on this !

**Comment by thecardcheat** [comment]
I think that about covers it. I am guessing that those 1.9 failures relate to #796? If you can think of anything else that will help this particular PR, let me know. Also, added myself to AUTHORS because I stumbled across it and could not find directions for/against it.

**Comment by trbs** [comment]
Thanks ! Yeah the 1.9 failures are related to our ```JSONField``` most important for that is to have a patch that works and not breaks anything :) Regretfully I do not have the time currently to really dive into the patches and work out what exactly is happening there, what changes and what a correct patch should look like... then the next best thing is having it heavily tested by users...

**Comment by EduardoCastanho** [comment]
hi ! 
I am using the github master version to run this command :
`python manage.py graph_models -a -g -o my_project_visualized.png `

But i am getting the folling error:
```
`Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.venvs/geosea/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.venvs/geosea/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/.venvs/geosea/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/.venvs/geosea/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/vagrant/django-extensions/django_extensions/management/utils.py", line 58, in inner
    ret = func(self, *args, **kwargs)
  File "/home/vagrant/django-extensions/django_extensions/management/commands/graph_models.py", line 91, in handle
    self.options_from_settings(options)
  File "/home/vagrant/django-extensions/django_extensions/management/commands/graph_models.py", line 120, in options_from_settings
    for option in self.graph_models_options:
AttributeError: 'Command' object has no attribute 'graph_models_options'
```

I check the code  and it seems to me that the method 'options_from_settings()' was forgotten in the solution to this issue.

Can you check this ?

Thanks

**Comment by thecardcheat** [comment]
Thanks for report. I have opened #835.

**Pull request merged**
