### PR TITLE
make render function django 2.1-compliant

### PR DESCRIPTION
**Pull request by swizzard**
See https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1

### CODE REVIEW

**Comment by trbs** [comment]
Thanks !

**Comment by swizzard** [comment]
@trbs thanks for merging this! any idea on when the next release on pip will be?

**Comment by trbs** [comment]
https://pypi.org/project/django-extensions/ :-)

**Comment by swizzard** [comment]
Fantastic! Thank you!

**Pull request merged**
